name: Deploy to Live Channel

on:
  push:
    branches:
      - master

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUD_FUNCTIONS_GET_STAR_4E4BA }}"
          projectId: cloud-functions-get-star-4e4ba
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks